### ISSUE TITLE
Attempted to run script and receive an Index Error

### ISSUE THREAD

**Issue by RocklessLobster** [TechnoSwiss/MPMD-AutoBedLevel-Cal#10]
Here's what I get after running the script (the script does start, it sends commands to the MPMD):

Traceback (most recent call last):

File "auto_cal_v2.py", line 240, in <module> main()

File "auto_cal_v2.py", line 229, in main calibrated, new_z, new_x, new_y, new_r = run_calibration(port, trial_x, trial_y, trial_z,r_value, max_runs, args.max_error)

File "auto_cal_v2.py", line 148, in run_calibration z_ave, x_ave, y_ave, c_ave = get_current_values(port)

File "auto_cal_v2.py", line 50, in get_current_values z_ave = float("{0:.3f}".format((float(z_axis_1[6]) + float(z_axis_2[6])) / 2))

IndexError: list index out of range

Is this an issue with my printer, like the script no longer works with the printer? I'm not familiar enough with the code or printer software to be sure. Thank you!

**Comment by TechnoSwiss** [comment]
I have one of the original Indie GoGo version of of the delta, and I've actually run into similar issues with v2 of the script myself, and haven't had the time to run through and sort it out. So generally I've stuck to using my original version of the script auto_cal.py there are a couple of fixes I need to get into place, the default steps/mm is for the older 8 steps/mm driver board, so if you have a newer printer with the 16 steps/mm board, you'll want to run it with the '-s 114.28' option. I haven't updated the code to account for changing the bed level without messing with the X/Y scaling, so if you've gone through Denis Brown's step-by-step, your scaling will be off again with the values found in this script.

**Comment by RocklessLobster** [comment]
So just to make sure I understand, I need to change the value in the first version of the script to the '-s 114.28' option? And otherwise run it unchanged and that should work?

Thanks for the quick reply by the way!

**Comment by TechnoSwiss** [comment]
If you have one of the newer printers, then yes I'd try the auto_cal.py version of the script, and just add the '-s 114.28' option on the command line when you run it. The difference is the driver for the stepper motors. The old ones were 8 steps, the new ones are 16. So if you have a newer version of the printer with the 16 step driver, and run the script without the -s option it will do the level operation in mid-air. If you're unsure which version of driver board you have, it's safer to run the script as-is, then add '-s 114.28' if you get the mid-air level attempt.

**Comment by RocklessLobster** [comment]
Thanks! So just to be clear, I add '-s 114.28' when running the program from the terminal or I add it into the program in python and then run the script from the terminal?

**Comment by TechnoSwiss** [comment]
So if you're currently running it like 'python auto_cal.py -p com3' then you'd want to run it like 'python auto_cal.py -p com3 -s 114.28'

**Comment by RocklessLobster** [comment]
Alright I ran that in the cmd line, and this time it gives me another index error but for line 58 of the script:

Traceback (most recent call last):
  File "auto_cal.py", line 58, in <module>
    print(z_axis_1[6].rstrip())
IndexError: list index out of range

With the '-s 114.28' added, the nozzle does go all the way to the bed now instead of stopping midair. I did peel off the stock bed material and just put blue tape on the bed plate, could that be causing an issue? 

Thanks again for all the help.

**Comment by TechnoSwiss** [comment]
That likely means the format of data coming from the printer on the newer firmware dosen't match what the script is expecting. I just merged in a bunch of changes from barryred that were supposedly tested with the new firmware, you could try re-pulling the script to get the changes and then give it a shot again.

**Comment by RocklessLobster** [comment]
Okay that helped progress a bit farther, I did start getting data from it, but then another error (just included everything from the G29 code):

MPMD: G29 Auto Bed Leveling
MPMD: Bed X: 0.000 Y: 50.000 Z: -7.791
MPMD: Bed X: 0.000 Y: 50.000 Z: -7.786
X-Axis :-7.791, -7.786 Average:-7.788
MPMD: Bed X: -43.300 Y: -25.000 Z: -7.925
MPMD: Bed X: -43.300 Y: -25.000 Z: -7.797
Y-Axis :-7.925, -7.797 Average:-7.861
MPMD: Bed X: 43.300 Y: -25.000 Z: -7.717
MPMD: Bed X: 43.300 Y: -25.000 Z: -7.729
Z-Axis :-7.717, -7.729 Average:-7.723
MPMD: Bed X: 0.000 Y: 0.000 Z: -8.576
MPMD: Bed X: 0.000 Y: 0.000 Z: -8.572
Center :-8.576, -8.572 Average:-8.574
X-Error: -0.065 Y-Error: -0.138 Z-Error: 0.0 C-Error: -0.7833
Configuring Delta Endstop Adjustment
Send: M666 X-0.065 Y-0.138 Z0.0
MPMD: -7.232 -7.839 -6.924
Exception occurred: Traceback (most recent call last):
  File "auto_cal.py", line 398, in main
    calibrator.calibrate()
  File "auto_cal.py", line 366, in calibrate
    trial_x, trial_y, trial_z, trial_r, calibrated = self.runCalibrationLoop(run_count, trial_x, trial_y, trial_z, trial_r)
  File "auto_cal.py", line 325, in runCalibrationLoop
    self.printer.setDeltaConfiguration(r=new_r, consumeOutput=True)
UnboundLocalError: local variable 'new_r' referenced before assignment

Progress at least?

**Comment by TechnoSwiss** [comment]
Looks like there was a bug in barryred's code, I think I fixed it, but I don't have the newer firmware to test it with. You'll have to pull the latest change, and give it another shot.

**Comment by RocklessLobster** [comment]
Okay it ran all the way through, the only issue now is that it hit the lowest overall error around calibration 4 (less than 0.02mm, but kept going, until the error (particuarly for the z-axis) was ~1.6. So I'm not sure if I can set it to use the settings from that calibration, or if it's just supposed to do that. I can post the full text if that would help.

**Comment by TechnoSwiss** [comment]
If the error is something like 0.021, it will keep the script from stopping, because it's greater than 0.02, but because of the formatting of the print-out that won't be obvious. You can just use the values from which ever run looks best to you.

**Comment by RocklessLobster** [comment]
So this run looked the best:

Moving to Home/Origin
Send: G28
Starting Automatic Bed Leveling, with probe value reporting.
Send: G29 P2 V4
MPMD: -8.515 -8.522 -8.414
MPMD: ok N0 P15 B11
MPMD: ok N0 P15 B12
MPMD: ok N0 P15 B13
MPMD: ok N0 P15 B14
MPMD: G29 Auto Bed Leveling
MPMD:
MPMD: Bed X: 0.000 Y: 50.000 Z: -8.579
MPMD: Bed X: 0.000 Y: 50.000 Z: -8.574
X-Axis :-8.579, -8.574 Average:-8.576
MPMD: Bed X: -43.300 Y: -25.000 Z: -8.537
MPMD: Bed X: -43.300 Y: -25.000 Z: -8.489
Y-Axis :-8.537, -8.489 Average:-8.513
MPMD: Bed X: 43.300 Y: -25.000 Z: -8.478
MPMD: Bed X: 43.300 Y: -25.000 Z: -8.499
Z-Axis :-8.478, -8.499 Average:-8.489
MPMD: Bed X: 0.000 Y: 0.000 Z: -8.533
MPMD: Bed X: 0.000 Y: 0.000 Z: -8.502
Center :-8.533, -8.502 Average:-8.518
X-Error: -0.087 Y-Error: -0.024 Z-Error: 0.0 C-Error: 0.008
Configuring Delta Endstop Adjustment
Send: M666 X-0.261 Y-0.08 Z0.0
MPMD: -8.534 -8.498 -8.474
Setting Delta Configuration
Send: M665 R64.0314
MPMD: -8.568 -8.533 -8.509

Would I just send those M666 and M665 commands to the printer, or am I sending something else? But again, thank you so much for doing all this quick work to help me run the script.

**Comment by TechnoSwiss** [comment]
Yes, you would want to send those commands to your printer every time you power the printer up. If you're using something like Octoprint there's a section for GCODE you want to send before the start of a print, you can put it in there (that's what I do). Or you could create a GCODE file that just has those commands in it, and run that file after you turn the printer on. Or you could add it to your start GCODE in Cura or whatever slicer you're using. I prefer the first 2 options because if you need to tweak those settings, you only have to change them one place, and all your GCODE files still work. If you put it in your startup GCODE for all your prints, then if you tweak it you'd have to tweak it in every file, but I know some people like to put it there so they don't forget to run it before they start printing.

**Comment by RocklessLobster** [comment]
Thank you so much! Hopefully I can run a test print soon and see how it turns out. I really appreciate the help.
